### ISSUE TITLE
Issue - Grid: Both figures are in the same column (column 1)

### ISSUE THREAD

**Issue by emahadzimustafic** [emahadzimustafic/components-on-a-grid#1]
Hi, I'm having an issue putting the second figure in column 2 row 2. I don't know what I'm missing. I thought it would naturally flow into that column with the right code, but it's not. It might be something to do with flexbox or some align css code. I'm not sure and I need help or a hint.

Thank you!

@anna-pokhilenko

**Comment by anna-pokhilenko** [comment]
Hello! Your code is beautifully written. There are a couple of little things to add there to make it work.
I am attaching a screenshot below
<img width="377" alt="Screen Shot 2021-09-22 at 4 21 58 PM" src="https://user-images.githubusercontent.com/55008926/134419001-f8d5d5ad-c3c0-4b75-aa42-68a2a7547a51.png">
.

**Comment by emahadzimustafic** [comment]
Thank you Anna!! I did that earlier and forgot to put in display contents for the main.
