### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by emahadzimustafic** [emahadzimustafic/components-on-a-grid#2]
Please let me know if my file doesn't work. I've tried uploading an mp4 and m4a file and they didn't go through. I'm more than happy to resend it through slack. Thanks!

[wd2-030-hadzimustafic-ema-componentsonagrid.zip](https://github.com/emahadzimustafic/components-on-a-grid/files/7230623/wd2-030-hadzimustafic-ema-componentsonagrid.zip)

@thatkidmadrid

**Comment by thatkidmadrid** [comment]
Hey Ema, I'm able to download the file, but it isn't playing anything back, so maybe you can try slack

**Comment by thatkidmadrid** [comment]
Hey Ema,

I was able to play the .mov you send through slack

looks and sounds great! and the `the end` was a nice touch haha

Overall well written and spoken; nothing to complain about. The gh-pages output looks good too 👍  keep it up

**Comment by emahadzimustafic** [comment]
Thank you!
